CPPFLAGS = -DREFERENCE_DB=\""nutrika.db"\" -DUSER_DB=\""user.db"\" -DHOME=\""APPDATA"\"
CFLAGS = -mms-bitfields -I/usr/i686-pc-mingw32/sys-root/mingw/include/gtk-2.0 -I/usr/i686-pc-mingw32/sys-root/mingw/lib/gtk-2.0/include -I/usr/i686-pc-mingw32/sys-root/mingw/include/atk-1.0 -I/usr/i686-pc-mingw32/sys-root/mingw/include/cairo -I/usr/i686-pc-mingw32/sys-root/mingw/include/gdk-pixbuf-2.0 -I/usr/i686-pc-mingw32/sys-root/mingw/include/pango-1.0 -I/usr/i686-pc-mingw32/sys-root/mingw/include/glib-2.0 -I/usr/i686-pc-mingw32/sys-root/mingw/lib/glib-2.0/include -I/usr/i686-pc-mingw32/sys-root/mingw/include/pixman-1 -I/usr/i686-pc-mingw32/sys-root/mingw/include/libpng14 -I/usr/i686-pc-mingw32/sys-root/mingw/include
LIBS = -Wl,-luuid -L/usr/i686-pc-mingw32/sys-root/mingw/lib -lgtk-win32-2.0 -lgdk-win32-2.0 -limm32 -lshell32 -lole32 -latk-1.0 -lpangocairo-1.0 -lgio-2.0  -lpangowin32-1.0 -lgdi32 -lpango-1.0 -lm -lcairo -lpixman-1 -lpng14 -lz -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lglib-2.0 -lintl -lsqlite3 -lpthread
CC=i686-pc-mingw32-gcc

nutrika.exe: 
	$(CC) $(CPPFLAGS) $(CFLAGS) -std=gnu99 -pedantic -o nutrika.exe src/gui.c src/database.c $(LIBS)

all: nutrika.exe 

