.TH NUTRIKA 1 "15 March 2011"
.SH NAME 
nutrika \- A nutrient content analyzer and calculator.
.SH SYNOPSIS
.B nutrika 
.SH DESCRIPTION 
.B nutrika 
is an application that displays food nutrient content.
.SH OPTIONS 
This program has no options.
.SH FILES
.TP
.B ~/.nutrika/user.db 
is the SQLite database file for user data. It will be created from the template user data file, if it is missing.
.TP
.B /usr/share/nutrika/nutrika.db 
is the reference database file containing nutrient information.
.SH SEE ALSO 
The project web site: <http://nutrika.sourceforge.net/>
.SH COPYRIGHT 
Copyright © 2011 Peter Sulyok.  License GPLv3+: GNU GPL version
3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.  There  is  NO
WARRANTY, to the extent permitted by law.

